# Generated by Django 5.1 on 2024-09-02 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('code', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('games', models.PositiveIntegerField()),
                ('wins', models.PositiveIntegerField()),
                ('winrate', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Augment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField()),
                ('games', models.PositiveIntegerField()),
                ('wins', models.PositiveIntegerField()),
                ('winrate', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.champion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('code', 'champion'), name='unique_augment_per_champion')],
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.PositiveIntegerField()),
                ('item2', models.PositiveIntegerField()),
                ('item3', models.PositiveIntegerField()),
                ('item4', models.PositiveIntegerField()),
                ('item5', models.PositiveIntegerField()),
                ('item6', models.PositiveIntegerField()),
                ('games', models.PositiveIntegerField()),
                ('wins', models.PositiveIntegerField()),
                ('winrate', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.champion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item1', 'item2', 'item3', 'item4', 'item5', 'item6', 'champion'), name='unique_items_per_champion')],
            },
        ),
    ]
