# Generated by Django 5.1 on 2024-09-03 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrismaticItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField()),
                ('games', models.PositiveIntegerField()),
                ('wins', models.PositiveIntegerField()),
                ('winrate', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.champion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('code', 'champion'), name='unique_prismatic_per_champion')],
            },
        ),
    ]
