# Generated by Django 5.1 on 2024-09-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_prismaticitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prismaticitem',
            name='champion',
        ),
        migrations.RemoveConstraint(
            model_name='items',
            name='unique_items_per_champion',
        ),
        migrations.RemoveField(
            model_name='items',
            name='item6',
        ),
        migrations.AddConstraint(
            model_name='items',
            constraint=models.UniqueConstraint(fields=('item1', 'item2', 'item3', 'item4', 'item5', 'champion'), name='unique_items_per_champion'),
        ),
        migrations.DeleteModel(
            name='PrismaticItem',
        ),
    ]
