# Generated by Django 5.1 on 2024-09-03 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_prismaticitem_champion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrismaticItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField()),
                ('games', models.PositiveIntegerField()),
                ('wins', models.PositiveIntegerField()),
                ('winrate', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='items',
            name='unique_items_per_champion',
        ),
        migrations.AddField(
            model_name='items',
            name='item6',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='items',
            constraint=models.UniqueConstraint(fields=('item1', 'item2', 'item3', 'item4', 'item5', 'item6', 'champion'), name='unique_items_per_champion'),
        ),
        migrations.AddField(
            model_name='prismaticitem',
            name='champion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.champion'),
        ),
        migrations.AddConstraint(
            model_name='prismaticitem',
            constraint=models.UniqueConstraint(fields=('code', 'champion'), name='unique_prismatic_per_champion'),
        ),
    ]
