# Generated by Django 5.1 on 2024-09-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_prismaticitem_remove_items_unique_items_per_champion_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='items',
            name='unique_items_per_champion',
        ),
        migrations.RemoveField(
            model_name='items',
            name='item5',
        ),
        migrations.RemoveField(
            model_name='items',
            name='item6',
        ),
        migrations.AddConstraint(
            model_name='items',
            constraint=models.UniqueConstraint(fields=('item1', 'item2', 'item3', 'item4', 'champion'), name='unique_items_per_champion'),
        ),
    ]
