# Generated by Django 5.1 on 2024-09-03 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_items_unique_items_per_champion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrismaticItem',
            new_name='Prismatic_item',
        ),
        migrations.CreateModel(
            name='Boot_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField()),
                ('games', models.PositiveIntegerField()),
                ('wins', models.PositiveIntegerField()),
                ('winrate', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.champion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('code', 'champion'), name='unique_boot_item_per_champion')],
            },
        ),
        migrations.CreateModel(
            name='Initial_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField()),
                ('games', models.PositiveIntegerField()),
                ('wins', models.PositiveIntegerField()),
                ('winrate', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.champion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('code', 'champion'), name='unique_initial_item_per_champion')],
            },
        ),
    ]
