# Generated by Django 5.1 on 2024-09-09 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rename_prismaticitem_prismatic_item_boot_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gold_augment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=1000)),
                ('games', models.PositiveIntegerField()),
                ('wins', models.PositiveIntegerField()),
                ('winrate', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.champion')),
            ],
        ),
        migrations.CreateModel(
            name='Prismatic_augment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=1000)),
                ('games', models.PositiveIntegerField()),
                ('wins', models.PositiveIntegerField()),
                ('winrate', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.champion')),
            ],
        ),
        migrations.CreateModel(
            name='Silver_augment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=1000)),
                ('games', models.PositiveIntegerField()),
                ('wins', models.PositiveIntegerField()),
                ('winrate', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.champion')),
            ],
        ),
        migrations.DeleteModel(
            name='Augment',
        ),
        migrations.AddConstraint(
            model_name='gold_augment',
            constraint=models.UniqueConstraint(fields=('code', 'champion'), name='unique_gold_augment_per_champion'),
        ),
        migrations.AddConstraint(
            model_name='prismatic_augment',
            constraint=models.UniqueConstraint(fields=('code', 'champion'), name='unique_prismatic_augment_per_champion'),
        ),
        migrations.AddConstraint(
            model_name='silver_augment',
            constraint=models.UniqueConstraint(fields=('code', 'champion'), name='unique_silver_augment_per_champion'),
        ),
    ]
