# Generated by Django 5.1 on 2024-09-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_gold_augment_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gold_augment',
            name='api_name',
            field=models.CharField(default='acceleratingsorcery_large.png', max_length=300),
        ),
        migrations.AddField(
            model_name='prismatic_augment',
            name='api_name',
            field=models.CharField(default='acceleratingsorcery_large.png', max_length=300),
        ),
        migrations.AddField(
            model_name='silver_augment',
            name='api_name',
            field=models.CharField(default='acceleratingsorcery_large.png', max_length=300),
        ),
    ]
